mutation acceptInvite($email: EmailAddress!, $password: Password!, $token: String!) {
  activateUser(input: { email: $email, password: $password, token: $token }) {
    token
    user {
      firstName
      lastName
      id
      type
      roleIds
    }
  }
}
