query getArticles($pagination: ArticlePaginationInput) {
  getArticles(input: {
    pagination: $pagination
  }) {
    paginationInfo {
      hasMore
      cursor
    }
    articles {
      id
      title
      status
      priority
      publishedAt
      slug
      previewToken
    }
  }
}
