mutation updateArticle(
                       $id: ID!,
                       $title: String!, 
                       $body: String!, 
                       $teaser: String!, 
                       $priority: ArticlePriority
                       $status: ArticleStatus
                       $publishedAt: Timestamp
                       $image: ImageInput
                       $playerMentions: [PlayerMentionInput]
                       $teamMentions: [TeamMentionInput]
                      ) {
  updateArticle(input: { 
    id: $id, 
    localeTitle: { en: $title } 
    localeTeaser: { en: $teaser }
    localeBody: { en: $body }
    priority: $priority
    status: $status
    publishedAt: $publishedAt
    image: $image
    playerMentions: $playerMentions
    teamMentions: $teamMentions
  }) {
    article {
      id
      title
      teaser
      body
      priority
      status
      playerMentions {
        id
        name
        slug
      }
      teamMentions {
        id
        name
        slug
      }
      image {
        publicId
      }
    }
  }
}
